@ stdcall TSPI_lineAnswer(long ptr str long)
@ stdcall TSPI_lineClose(ptr)
@ stdcall TSPI_lineCloseCall(ptr)
@ stdcall TSPI_lineGetAddressCaps(long long long long ptr)
@ stdcall TSPI_lineGetCallStatus(ptr ptr)
@ stdcall TSPI_lineGetDevCaps(long long long ptr)
@ stdcall TSPI_lineMakeCall(long ptr ptr ptr wstr long ptr)
@ stdcall TSPI_lineNegotiateTSPIVersion(long long long ptr)
@ stdcall TSPI_lineOpen(long ptr ptr long ptr)
@ stdcall TSPI_lineDrop(long ptr str long)
@ stdcall TSPI_providerEnumDevices(long ptr ptr ptr ptr ptr)
@ stdcall TSPI_providerInit(long long long long long long ptr ptr)
@ stdcall TSPI_providerShutdown(long long)